import type { CatKnowledge } from '../types/game';

export const catKnowledge: CatKnowledge[] = [
  {
    id: 'k1',
    category: 'diet',
    categoryName: '饮食',
    title: '猫咪需要多喝水',
    content: '猫咪的祖先来自沙漠，天生不太爱喝水。主人应该多放置几个水碗，或者使用流动饮水机，鼓励猫咪多喝水，预防泌尿系统疾病。',
    emoji: '💧',
  },
  {
    id: 'k2',
    category: 'diet',
    categoryName: '饮食',
    title: '不能喂猫咪牛奶',
    content: '大多数成年猫咪乳糖不耐受，喝牛奶会导致腹泻。可以给猫咪喝专门的宠物羊奶粉，或者舒化奶（无乳糖牛奶）。',
    emoji: '🥛',
  },
  {
    id: 'k3',
    category: 'diet',
    categoryName: '饮食',
    title: '定时定量喂食',
    content: '成年猫每天喂2-3次即可，定时定量有助于猫咪消化系统健康。不要一直把猫粮放着让猫随便吃，容易导致肥胖。',
    emoji: '🍚',
  },
  {
    id: 'k4',
    category: 'diet',
    categoryName: '饮食',
    title: '这些食物猫咪不能吃',
    content: '洋葱、大蒜、葡萄、葡萄干、巧克力、咖啡因、酒精对猫咪都是有毒的，一定要收好，绝对不能让猫咪吃到!',
    emoji: '⚠️',
  },
  {
    id: 'k5',
    category: 'health',
    categoryName: '健康',
    title: '定期接种疫苗',
    content: '猫咪需要接种猫三联疫苗（预防猫瘟、猫鼻支、猫杯状病毒）和狂犬疫苗。幼猫8周开始接种，之后每年加强一次。',
    emoji: '💉',
  },
  {
    id: 'k6',
    category: 'health',
    categoryName: '健康',
    title: '每月体外驱虫',
    content: '即使是室内猫也需要定期驱虫。体外驱虫每月一次，体内驱虫每3个月一次，预防跳蚤、耳螨、绦虫等寄生虫。',
    emoji: '🐛',
  },
  {
    id: 'k7',
    category: 'health',
    categoryName: '健康',
    title: '观察猫咪的大小便',
    content: '猫咪的大小便能反映健康状况。正常尿液是淡黄色的，粪便应该是成形的棕色。如果出现软便、便血、排尿困难等，要及时就医。',
    emoji: '🚽',
  },
  {
    id: 'k8',
    category: 'health',
    categoryName: '健康',
    title: '猫咪应激反应',
    content: '猫咪很容易应激，环境变化、陌生人、搬家都可能导致。应激会引起免疫力下降，甚至引发猫传腹等严重疾病，要尽量减少刺激。',
    emoji: '😿',
  },
  {
    id: 'k9',
    category: 'behavior',
    categoryName: '行为',
    title: '猫咪缓慢眨眼=我爱你',
    content: '当猫咪对着你慢慢眨眼时，这是猫咪表达信任和爱意的方式，相当于猫咪的"飞吻"。你也可以慢慢眨眼回应它哦~',
    emoji: '👀',
  },
  {
    id: 'k10',
    category: 'behavior',
    categoryName: '行为',
    title: '踩奶是幸福的表现',
    content: '猫咪踩奶是幼年吃奶时的遗留行为，当它们踩奶时，说明此刻非常放松、有安全感，把你当成了猫妈妈~',
    emoji: '🐾',
  },
  {
    id: 'k11',
    category: 'behavior',
    categoryName: '行为',
    title: '尾巴的情绪',
    content: '尾巴竖起来=开心自信；尾巴夹起来=害怕紧张；尾巴快速摆动=生气烦躁；尾巴慢慢摆动=专注思考。',
    emoji: '〰️',
  },
  {
    id: 'k12',
    category: 'behavior',
    categoryName: '行为',
    title: '咕噜声不止是开心',
    content: '猫咪咕噜声通常表示开心，但受伤、生病、紧张时也会咕噜来自我安慰。如果猫咪一直咕噜且状态不对，要留意。',
    emoji: '💤',
  },
  {
    id: 'k13',
    category: 'environment',
    categoryName: '环境',
    title: '猫砂盆摆放位置',
    content: '猫砂盆要放在安静、通风、猫咪容易到达的地方，远离食盆和水盆。多猫家庭建议猫砂盆数量=猫数+1。',
    emoji: '📦',
  },
  {
    id: 'k14',
    category: 'environment',
    categoryName: '环境',
    title: '每天清理猫砂',
    content: '猫咪非常爱干净，猫砂盆至少每天清理1-2次，每周彻底更换猫砂并清洗猫砂盆。否则猫咪可能会拒绝使用，到处乱拉。',
    emoji: '🧹',
  },
  {
    id: 'k15',
    category: 'environment',
    categoryName: '环境',
    title: '给猫咪垂直空间',
    content: '猫咪喜欢待在高处，这样有安全感。准备猫爬架、柜子顶等高处空间，能让猫咪更开心，减少压力和行为问题。',
    emoji: '🏔️',
  },
  {
    id: 'k16',
    category: 'environment',
    categoryName: '环境',
    title: '封窗很重要!',
    content: '猫咪对窗外很好奇，而且会捕捉窗外的鸟，很容易坠楼。无论高层低层都要封窗，使用隐形防护网或金刚纱窗，杜绝隐患。',
    emoji: '🪟',
  },
];

export const knowledgeCategories = [
  { key: 'diet', name: '🍽️ 饮食' },
  { key: 'health', name: '💊 健康' },
  { key: 'behavior', name: '😸 行为' },
  { key: 'environment', name: '🏠 环境' },
] as const;
