import type { PrepPurchase } from '../types/game';

export const prepItems: PrepPurchase[] = [
  {
    category: 'catFood',
    id: 'food-basic',
    name: '基础猫粮',
    emoji: '🍚',
    description: '补充普通猫粮，增加食物储备。',
    cost: 30,
    effect: { foodSupply: 40 },
  },
  {
    category: 'catFood',
    id: 'food-premium',
    name: '高级猫粮',
    emoji: '🥩',
    description: '高级猫粮不仅补充储备，还能稍微提升猫咪心情。',
    cost: 80,
    effect: { foodSupply: 80, catMood: 8 },
  },
  {
    category: 'catFood',
    id: 'food-super',
    name: '豪华猫粮套餐',
    emoji: '🍱',
    description: '顶级猫粮，全面提升食物储备和猫咪状态。',
    cost: 150,
    effect: { foodSupply: 100, catMood: 15, catHealth: 5 },
  },
  {
    category: 'cleaning',
    id: 'clean-basic',
    name: '基础清洁',
    emoji: '🧽',
    description: '清洁猫砂盆和基础卫生。',
    cost: 25,
    effect: { litterCleanliness: 60, hygiene: 30 },
  },
  {
    category: 'cleaning',
    id: 'clean-deep',
    name: '深度清洁',
    emoji: '🧴',
    description: '彻底清洁店铺，全面提升环境卫生。',
    cost: 70,
    effect: { litterCleanliness: 100, hygiene: 70 },
  },
  {
    category: 'cleaning',
    id: 'clean-premium',
    name: '消毒服务',
    emoji: '✨',
    description: '专业消毒服务，极大提升卫生状况，利于猫咪健康。',
    cost: 120,
    effect: { litterCleanliness: 100, hygiene: 100, catHealth: 8 },
  },
  {
    category: 'equipment',
    id: 'equip-repair',
    name: '设备保养',
    emoji: '🔧',
    description: '对咖啡机进行日常保养，提升耐久度。',
    cost: 40,
    effect: { machineDurability: 40 },
  },
  {
    category: 'equipment',
    id: 'equip-overhaul',
    name: '设备大修',
    emoji: '🛠️',
    description: '全面检修设备，大幅提升耐久度。',
    cost: 100,
    effect: { machineDurability: 85 },
  },
  {
    category: 'catTreatment',
    id: 'treat-vitamin',
    name: '营养补充',
    emoji: '💊',
    description: '给所有猫咪补充维生素，小幅提升健康。',
    cost: 50,
    effect: { catHealth: 10 },
  },
  {
    category: 'catTreatment',
    id: 'treat-checkup',
    name: '体检服务',
    emoji: '🩺',
    description: '为猫咪做全面体检，显著提升健康状态。',
    cost: 90,
    effect: { catHealth: 25 },
  },
  {
    category: 'catTreatment',
    id: 'treat-full',
    name: '全面治疗',
    emoji: '🏥',
    description: '治愈所有生病的猫咪，并全面提升健康和心情。',
    cost: 200,
    effect: { catCureAll: true, catHealth: 40, catMood: 20 },
  },
];

export const categoryLabels: Record<PrepPurchase['category'], { name: string; emoji: string; color: string }> = {
  catFood: { name: '猫粮采购', emoji: '🍚', color: 'from-amber-100 to-amber-200' },
  cleaning: { name: '清洁用品', emoji: '🧹', color: 'from-sky-100 to-sky-200' },
  equipment: { name: '设备保养', emoji: '🔧', color: 'from-slate-100 to-slate-200' },
  catTreatment: { name: '猫咪治疗', emoji: '💊', color: 'from-rose-100 to-rose-200' },
};
